# Site
name: "Shreya Ponnamma"
title: "MyBlogs"
description: "An Engineering student blogging about all sort o stuff."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /blog
google_analytics: 'UA-xxxxxxxx-1'
include: ["_pages"]
permalink: /:title/
email: shreyaponnamma@outlook.com
linkedin: https://www.linkedin.com/in/shreya-ponnamma-13578b148
twitter: https://twitter.com/shreya_ponnamma

# Authors
authors:
  shreya:
    name: Shreya Ponnamma
    display_name: Shreya Ponnamma
    avatar: assets/images/avatar.svg
    email: shreyaponnamma@outlook.com
    twitter: https://twitter.com/shreya_ponnamma
    description: "An Engineering student."
    linkedin: https://www.linkedin.com/in/shreya-ponnamma-13578b148


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
